### ISSUE TITLE
Can not disable sound

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-solutions/multibit-hd#602] opened 2015-06-10 20:38 UTC
[This video](https://googledrive.com/host/0B0oLc-dc--NeWVl1Z1BqaG5lbnM) shows me trying to disable sound completely which seems not to work. I almost got a heart attack by the receiving-sound notification. ;)

**Comment by gary-rowe** [comment] 2015-06-11 12:11
Thanks for the feedback (and sorry for the noise!)

Steps to replicate are:

* Preferences | Sound | Set both to No
* Click Apply
* Re-enter and observe one or the other set to Yes

**Comment by gary-rowe** [comment] 2015-06-11 12:25
This was caused by incorrect `Configuration` state handling in the sound preference view.

Ready for review and close.

**Comment by jim618** [comment] 2015-06-11 15:33
The configuration works but it doesn't actually suppress the alert sound.
For instance, set sound on alert to No, apply and then switch and enter an incorrect password.
You still hear an alert sound.

**Comment by gary-rowe** [comment] 2015-06-12 09:39
Yes, this extra beep is caused by the `LookAndFeel` in use by Swing itself. I've applied a suitable override during startup so this should give consistent behaviour throughout.

I've also added button enable/disable behaviour to accentuate the user's choice which makes for quicker cognition when looking at the current selection.

Ready for review and close.

**Comment by jim618** [comment] 2015-06-12 10:26
Confirmed that switching off the sounds works both for alert and receive notifications.
Also checked they reappear when switched back on.
Confirmed enable/ disable of play buttons matches play choice state.

Closing

**Closed by jim618** 2015-06-12 10:26 UTC
Labels: awaiting review
