### ISSUE TITLE
Font title in lightboxes looks poor on Windows (no anti-aliasing)

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#613] opened 2015-06-17 15:29 UTC
On a Toshiba Windows 8 test machine the MBHD lightbox fonts look poor. The font is not antialiased.

edit: this is specifically the font used in the title

**Comment by gary-rowe** [comment] 2015-06-17 16:18
Might be good to have a screen shot for a before/after comparison.

**Comment by gary-rowe** [comment] 2015-06-17 16:20
This is a duplicate of #384 which contains more detail and should be re-opened.

**Closed by gary-rowe** 2015-06-17 16:20 UTC
