### ISSUE TITLE
Crash on startup on OSX 10.11: 

### ISSUE THREAD

**Issue by bfod** [bitcoin-solutions/multibit-hd#761] opened 2015-10-18 15:42 UTC
I just installed Multibit HD 0.1.3 on OSX 10.11. It won't start, it throws this error:

`java.lang.ClassCastException: org.slf4j.impl.Log4jLoggerAdapter cannot be cast to ch.qos.logback.classic.Logger
	at org.multibit.hd.core.logging.LoggingFactory.getCleanRoot(LoggingFactory.java:119)
	at org.multibit.hd.core.logging.LoggingFactory.bootstrap(LoggingFactory.java:34)
	at org.multibit.hd.ui.MultiBitHD.start(MultiBitHD.java:119)
	at org.multibit.hd.ui.MultiBitHD.main(MultiBitHD.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.MacLauncher.main(Unknown Source)`

**Comment by gary-rowe** [comment] 2015-10-18 18:14
This appears to be a duplicate of #400 so closing this and re-opening that.

**Closed by gary-rowe** 2015-10-18 18:14 UTC
