### ISSUE TITLE
NPE in save payment request

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#763] opened 2015-10-19 13:23 UTC
error report uploaded. Id: bba599d

MultiBit HD version: 0.1.3
Operating system: 64 6.3 Windows 8.1

No user notes

Number of stack traces: 1
First stack trace:
java.lang.NullPointerException: null
	at org.multibit.hd.ui.views.wizards.request_bitcoin.RequestBitcoinEnterDetailsPanelView.savePaymentRequest(RequestBitcoinEnterDetailsPanelView.java:245) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.request_bitcoin.RequestBitcoinEnterDetailsPanelView.beforeHide(RequestBitcoinEnterDetailsPanelView.java:212) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractWizard.hide(AbstractWizard.java:226) ~[multibit-hd.jar:na]
	at org.multibit.hd.ui.views.wizards.AbstractWizard$3.actionPerformed(AbstractWizard.java:312) ~[multibit-hd.jar:na]

**Comment by gary-rowe** [comment] 2015-11-23 21:42
Duplicate of #798. Closing.

**Closed by gary-rowe** 2015-11-23 21:42 UTC
Labels: upload
