### ISSUE TITLE
  Bug report: Beta 7 has nothing visible in UI tabs

### ISSUE THREAD

**Issue by hughht5** [bitcoin-solutions/multibit-hd#437] opened 2015-03-01 15:59 UTC
Operating System: Mac OSX Yosemite
  MultiBit HD Version: 0.0.7 beta
  Steps to replicate the problem: open the program.
see image attached
![screen shot 2015-03-01 at 15 57 26](https://cloud.githubusercontent.com/assets/629186/6431587/ed545816-c02b-11e4-8e80-818aee2334a1.png)

**Comment by jim618** [comment] 2015-03-01 16:05
Is that immediately after opening ?

**Comment by hughht5** [comment] 2015-03-02 10:47
It's after choosing a wallet and typing in my password. It connects and synchronises but never loads any of the UI. I tried restarting the app several times and no change.

**Comment by jim618** [comment] 2015-03-02 11:05
Ok - thanks for your feedback.
It sounds like an initialisation problem with a map we have of all the main screens.

**Comment by jim618** [comment] 2015-03-03 17:08
Changed DetailView so that it loads Screens on demand so user should never encounter a blank main screen

Awaiting code review by @gary-rowe 

I'll then create a test installer and request @hughht5 to retest on his machine.

**Comment by gary-rowe** [comment] 2015-03-04 11:18
Verified screens are working. Good to go for a 0.0.0 installer.

**Comment by gary-rowe** [comment] 2015-03-04 19:54
Marking as bounced back to indicate next step is ready.

**Comment by jim618** [comment] 2015-03-07 15:21
@hughht5 I have built a Mac test installer and uploaded to:
https://multibit.org/releases/multibit-hd/multibit-hd-0.0.0/

It's the file multibit-hd-0.0.0.dmg

Can you please try it out on your Mac OSX Yosemite machine and let us know if this fixes the original bug (or not) ?

Thanks in advance

Jim

**Comment by gary-rowe** [comment] 2015-03-12 09:49
Spoke to @hughht5 and he was able to give the following feedback:

"First time I loaded it up I got the attached error and it crashed. I reloaded and it works fine now on all the buttons except the 'Contacts' button which still does nothing."

![screen shot 2015-03-12 at 09 16 31](https://cloud.githubusercontent.com/assets/342133/6615551/bf91cd22-c89c-11e4-9e3d-a0c9e71ce40f.png)

The Payments error was most likely caused by a failed load of the screens early on. We'd need logs to fully debug it. The Contacts screen not showing may be a more complex race condition - I suspect an extremely fast laptop is being used.

**Comment by hughht5** [comment] 2015-03-12 10:02
I'm using a mac pro retina so it's pretty quick I suppose.
I've tried clicking all the buttons on the left several times - they all work every time except the contacts which never show.

**Comment by hughht5** [comment] 2015-03-12 10:14
I've uploaded the logs here: http://filebin.ca/1uYXuRroEErl

**Comment by jim618** [comment] 2015-03-12 12:21
I suspect the errors you are seeing are all knock on effects of that payment db not being correct.
You can validate this by:
1) closing MBHD
2) renaming the payments.aes given in the path in the dialog above
3) restarting MBHD

You won't have some of your payments comments and fiat equivalent (which are stored in this file).
If this clears up the other issues you have posted then we know that was the root cause.

**Comment by hughht5** [comment] 2015-03-12 12:25
I closed MBHD - I renamed payments.aes to payments.aes.bak - reopened MBHD.
A new payments.aes appeared (as expected).

All the bugs here: https://github.com/bitcoin-solutions/multibit-hd/issues/461 are still bugs.

**Comment by jim618** [comment] 2015-03-12 15:11
OK thanks Hugh

**Comment by jim618** [comment] 2015-03-17 14:25
I've marked this as awaiting issue as it is related to/ dupe of  #461

**Comment by jim618** [comment] 2015-03-18 14:05
Proposed fix in #470

**Comment by gary-rowe** [comment] 2015-04-01 20:33
This requires @hughht5 to verify so marking as "awaiting installer" to prompt the creation of a 0.0.0 installer pending close.

**Comment by jim618** [comment] 2015-04-02 11:02
I have uploaded a test installer for @hughht5 to test here:
https://beta.multibit.org/releases/multibit-hd/multibit-hd-0.0.0/

It won't fix the existing wallet but if you create a new wallet you should be able to change password etc ok.

Awaiting review and closing

**Comment by jim618** [comment] 2015-04-08 10:12
I've closed this as neither @gary-rowe or I are seeing this problem.
@hughht5 if when you retest it it's still a problem open it again.

**Closed by jim618** 2015-04-08 10:12 UTC
Labels: awaiting review
