### ISSUE TITLE
Clicking PaymentRequest file does not launch MultiBit HD

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#455] opened 2015-03-09 20:19 UTC
The installer needs to ensure that `.bitcoinpaymentrequest` files are registered with MultiBit HD and trigger an application launch just like BIP21 Bitcoin URIs.

If possible this could be stretched to include a drag and drop operation although cross platform/application support is very tricky borne out by experience with MultiBit Classic and QR code handling.

**Comment by gary-rowe** [comment] 2015-03-16 15:45
Added support for `.bitcoinpaymentrequest` file association to Beta 8 installer.

**Comment by gary-rowe** [comment] 2015-03-16 21:50
Interim review for OS X. To verify do the following:

* build the latest multibit-hd.jar and incorporate it into the latest 0.0.8beta installer
* install to OS X as normal (observe new "associate file extension" screen)
* navigate to `mbhd-swing/src/test/resources/fixtures/payments` in Finder
* double click one or both of the payment request files (may need to use right click open with)
* observe MultiBit HD starting
* unlock wallet and observe one or two payment request alerts depending on starting conditions

This may work out of the box for Windows but it's not been tested yet.

**Comment by jim618** [comment] 2015-03-17 11:07
It works correctly when MBHD is NOT already started i.e. you see the alert ok and everything.

If MBHD is already started nothing appears on the UI. No alert.
In the logs you see:
```
[2015-03-17 11:05:28,179] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenFilesHandler - Received present URI request of 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-swing/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' 
[2015-03-17 11:05:28,179] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenFilesHandler - Broadcasting to 1 listener(s) 
[2015-03-17 11:05:28,179] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoking method OpenFilesEvent.getFiles 
[2015-03-17 11:05:28,180] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Decoding URI from 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-swing/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' 
[2015-03-17 11:05:28,180] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Using 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-swing/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' to create payment protocol session summary 
[2015-03-17 11:05:28,180] INFO  [AWT-EventQueue-0] o.m.h.c.s.PaymentProtocolService - Probing 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-swing/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' 
```
So it looks like the request is being passed to the instance

**Comment by gary-rowe** [comment] 2015-03-17 11:29
Yeah, this is the `false` flag delaying the alert when adding to the queue before the wallet is unlocked. I'll tidy it up tonight.

**Comment by gary-rowe** [comment] 2015-03-17 20:46
Adjusted flag so that if a wallet is present it will show the alert as well as process the payment. 

To quickly verify this behaviour add the following code snippet into `MainController.onPreferencesEvent`:

```
   final File file1 = new File("mbhd-swing/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest");
    final File file2 = new File("mbhd-swing/src/test/resources/fixtures/payments/localhost-signed.bitcoinpaymentrequest");

    GenericOpenFilesEvent e2 = new GenericOpenFilesEvent() {
      @Override
      public List<File> getFiles() {
        return Lists.newArrayList(file1, file2);
      }

      @Override
      public String getSearchTerm() {
        return null;
      }
    };
    onOpenFilesEvent(e2);
```

Fire up the application from the IDE and trigger the external event handler using the Preference selection from the OS X menu. This will emulate the EAWT event without needing to build a full installer.

**Comment by gary-rowe** [comment] 2015-03-17 21:24
On Windows the following error was seen during startup:
```
java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: C:\Workspaces\Java\BitcoinSolutions\multibit-hd\mbhd-swing\src\test\resources\fixtures\payments\dblsha-signed.bitcoinpaymentrequest
	at java.net.URI.create(Unknown Source)
	at org.multibit.hd.ui.services.ExternalDataListeningService.parsePaymentSessionSummary(ExternalDataListeningService.java:377)
	at org.multibit.hd.ui.services.ExternalDataListeningService.addToQueues(ExternalDataListeningService.java:241)
	at org.multibit.hd.ui.services.ExternalDataListeningService.<init>(ExternalDataListeningService.java:87)
	at org.multibit.hd.ui.MultiBitHD.initialiseListeningService(MultiBitHD.java:169)
	at org.multibit.hd.ui.MultiBitHD.start(MultiBitHD.java:114)
	at org.multibit.hd.ui.MultiBitHD.main(MultiBitHD.java:61)
```
This indicates that the file association was made correctly (it applied the MultiBit HD icon to the payment request files) but the URI parsing on the command line is currently weak.

**Comment by jim618** [comment] 2015-03-18 11:58
This is ALMOST there. :-)

I rebuilt the installer and tried it out IRL. If I have MBHD up and running a new alert is seen after I double click the bitcoinpaymentrequest file.

If I have gone through the Credentials wizard / Wallet start up screen it works fine, but if I have the credentials screen present I see the alert in the background, click Finish and then the alert disappears.
(Looks like it is not being replayed after a mainView refresh.


If MBHD is not started double clicking the payment request file starts MBHD and everything works fine. No regression there.

**Comment by gary-rowe** [comment] 2015-03-19 22:01
I've tested operations on Windows and observed that each PaymentRequest file causes a fresh instance of MultiBit HD to be launched (you'd have thought `arg[]` would have been filled but no). If the PaymentRequest file is double clicked then we get a launch (previously it borked on URI parsing) and if the wallet is unlocked the alert will show. If not then it is deferred until a wallet is unlocked or lost on application exit.

Ready for review and close.

**Comment by jim618** [comment] 2015-03-20 11:55
I rebuilt the installer and reinstalled.
I'm not seeing any alerts (whether MBHD is open, closed, on credentials screen).

It looks like the parameter is getting into MBHD - it's just not showing an alert:

```
[2015-03-20 11:50:39,020] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Created event GenericOpenFilesEvent 
[2015-03-20 11:50:39,020] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoking DefaultOpenFilesHandler.openFiles(GenericOpenFilesEvent)  
[2015-03-20 11:50:39,020] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenFilesHandler - Called 
[2015-03-20 11:50:39,020] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenFilesHandler - Event class is $Proxy15 
[2015-03-20 11:50:39,020] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoking method OpenFilesEvent.getFiles 
[2015-03-20 11:50:39,020] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenFilesHandler - Received present URI request of 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' 
[2015-03-20 11:50:39,020] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenFilesHandler - Broadcasting to 1 listener(s) 
[2015-03-20 11:50:39,020] DEBUG [main] o.m.h.u.p.b.m.MacApplication - Adding GenericAboutHandler 
[2015-03-20 11:50:39,030] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoking method OpenFilesEvent.getFiles 
[2015-03-20 11:50:39,031] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Parsing raw data: 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' 
[2015-03-20 11:50:39,031] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Decoding URI from 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' 
[2015-03-20 11:50:39,031] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Using 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' to create payment protocol session summary 
```

and
```
[2015-03-20 11:51:08,368] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoked. NativeMethod=openFiles, method args length=1 
[2015-03-20 11:51:08,368] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Building invocation handler. Native OpenFilesEvent -> GenericOpenFilesEvent 
[2015-03-20 11:51:08,368] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Building proxy for generic event 
[2015-03-20 11:51:08,368] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Created event GenericOpenFilesEvent 
[2015-03-20 11:51:08,368] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoking DefaultOpenFilesHandler.openFiles(GenericOpenFilesEvent)  
[2015-03-20 11:51:08,369] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenFilesHandler - Called 
[2015-03-20 11:51:08,369] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenFilesHandler - Event class is $Proxy15 
[2015-03-20 11:51:08,369] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoking method OpenFilesEvent.getFiles 
[2015-03-20 11:51:08,369] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenFilesHandler - Received present URI request of 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' 
[2015-03-20 11:51:08,369] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenFilesHandler - Broadcasting to 1 listener(s) 
[2015-03-20 11:51:08,369] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoking method OpenFilesEvent.getFiles 
[2015-03-20 11:51:08,369] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Parsing raw data: 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' 
[2015-03-20 11:51:08,369] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Decoding URI from 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' 
[2015-03-20 11:51:08,369] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Using 'file:/Users/jim/IdeaProjects/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/dblsha-signed.bitcoinpaymentrequest' to create payment protocol session summary 
[2015-03-20 11:51:08,369] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Checking for alert requirement 
```

This is on my Mac

**Comment by gary-rowe** [comment] 2015-03-20 12:09
That "Checking for alert requirement" means that it will fire the alert if the BitcoinURI or PaymentRequest queues have entries. Perhaps the data hasn't parsed correctly and is being silently ignored. What does the probe result say?

**Comment by jim618** [comment] 2015-03-20 13:06
If I fire up MBHD in the IDE with with a param pointing to 'localhost-signed.bitcoinpaymentrequest' I get the alert as shown in screenshot.
If I click 'Yes' the alert dismisses but I don't see a lightbox.
Could be related.
No errors in the log.
![screen shot 2015-03-20 at 13 04 48](https://cloud.githubusercontent.com/assets/919427/6751934/ba5f9b5c-cf01-11e4-9c75-a82411ea0026.png)

**Comment by jim618** [comment] 2015-03-21 12:29
With the current code (Saturday morning) if I click on a BIP21 bitcoin URI (the one on multibit.org) I am not seeing an alert appear.
This was tested by building the multibit-hd.jar and copying it into the MultBitHD app. This seems the 'truest' way to test it.

Relevant log entry:
```
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoked. NativeMethod=openURI, method args length=1 
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Building invocation handler. Native OpenURIEvent -> GenericOpenURIEvent 
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Building proxy for generic event 
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Created event GenericOpenURIEvent 
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoking DefaultOpenURIHandler.openURI(GenericOpenURIEvent)  
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenURIHandler - Called 
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenURIHandler - Event class is $Proxy13 
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoking method OpenURIEvent.getURI 
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenURIHandler - Received present URI request of 'bitcoin:1AhN6rPdrMuKBGFDKR1k9A8SCLYaNgXhty?amount=0.01&label=Please%20donate%20to%20multibit.org' 
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.h.DefaultOpenURIHandler - Broadcasting to 1 listener(s) 
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.p.b.m.BaseMacInvocationHandler - Invoking method OpenURIEvent.getURI 
[2015-03-21 11:58:50,553] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Parsing raw data: 'bitcoin:1AhN6rPdrMuKBGFDKR1k9A8SCLYaNgXhty?amount=0.01&label=Please%20donate%20to%20multibit.org' 
[2015-03-21 11:58:50,554] DEBUG [AWT-EventQueue-0] o.m.h.u.s.ExternalDataListeningService - Decoding BIP21 Bitcoin URI from 'bitcoin:1AhN6rPdrMuKBGFDKR1k9A8SCLYaNgXhty?amount=0.01&label=Please%20donate%20to%20multibit.org' 
```

**Comment by gary-rowe** [comment] 2015-03-21 13:25
Yeah, it's not quite ready for testing yet. There's been a fair bit of refactoring going on.

**Comment by gary-rowe** [comment] 2015-03-21 13:47
OK, this one checks out on Windows and OS X. It should handle single and multiple files offered up. No visibility of the alert until a wallet is unlocked. Errors should show up in red, valid requests in pink. There is still the issue of not opening a failed PKI request (e.g. localhost signed) but I think that should be a separate issue now.

Also take a look at the History which now records all alerts and their messages to assist audit later.

Ready for review and close.

**Comment by jim618** [comment] 2015-03-21 16:53
I rebuilt the multi bit-hd.jar and put it in my MultiBit HD.
Tried it out with various payment requests, BIP70 and BIP21. MBHD started and not.
All the alerts appear ok. Closing.

**Closed by jim618** 2015-03-21 16:53 UTC
Labels: awaiting review, bip70
