### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by kornelius93** [bitcoin-solutions/multibit-hd#838] opened 2016-01-15 22:18 UTC
Bug report
  Operating System: Windows 10
  MultiBit HD Version:0.1.2

![image](https://cloud.githubusercontent.com/assets/16726480/12366860/ec805222-bbee-11e5-8ab6-0d3bd0518c04.png)

![image](https://cloud.githubusercontent.com/assets/16726480/12367805/4bf3112a-bbf6-11e5-8479-9c874d28e488.png)

![image](https://cloud.githubusercontent.com/assets/16726480/12367810/582bc11c-bbf6-11e5-8969-12d9ec8186fc.png)
 
![image](https://cloud.githubusercontent.com/assets/16726480/12367824/7fa79860-bbf6-11e5-901b-23a48ad73255.png)

Waiting for my money about 2 days already.

  I've removed personally identifying information:

**Comment by gary-rowe** [comment] 2016-01-16 15:53
From the screen shots it may be that you've set your transaction fee too low and the miners are ignoring it. Generally using the defaults in the latest version of MultiBit HD 0.1.4 will have a good chance of rapid inclusion in a block. You should upgrade your MultiBit HD to avoid this happening in the future.

Since this is an issue with the block chain and miner acceptance, I'm going to close this issue.

**Closed by gary-rowe** 2016-01-16 15:53 UTC

**Comment by kornelius93** [comment] 2016-01-16 16:50
So, I won't get my money back or what?

**Comment by jim618** [comment] 2016-01-16 16:53
It'll get into a block eventually but it could be quite a while.

**Comment by kornelius93** [comment] 2016-01-16 16:54
Week, month or how long approximately?

**Comment by jim618** [comment] 2016-01-16 16:58
Work out the fee rate you paid and have a look at http://www.cointape.com for network stats

**Comment by kornelius93** [comment] 2016-01-16 17:14
Do I need to write a report to Bitstamp? Or this error means only that I paid not enough fee and that I just have to wait? I've done it before like a 100 times with the same fee and everything was OK.

**Comment by jim618** [comment] 2016-01-16 17:24
Fees are a bit annoying with bitcoin at the moment as they make life difficult for everyone.
With the latest MultiBIt HD code there is a slider (in Preferences | Fees) that you can adjust.

If you have an old version the fees weren't adjustable - a month or two ago transaction fees went up x5 which is probably the problem.

You'll just have to be patient I am afraid

**Comment by kornelius93** [comment] 2016-01-16 17:26
Is there a chance that they will never come back?

**Comment by jim618** [comment] 2016-01-16 17:53
It's possible that the bitcoin network forgets the transaction "because it is old and they don't like it".
In this case you can just do a "Manage wallet | repair wallet" and you can resync to what is on the blockchain. In this case it will be as if the transaction never happened and you'll see the bitcoin back in your wallet.

A bitcoin transaction is either succesful (i.e. the recipient has the bitcoin) or eventually fails (in which case you have the bitcoin). It can't get lost.

**Comment by kornelius93** [comment] 2016-01-16 18:00
But I've already repaired it and nothing changed.

**Comment by kornelius93** [comment] 2016-01-17 11:33
Everything is fine, I got my money. Thank you a lot for your help.

**Comment by jim618** [comment] 2016-01-17 12:18
Good to hear it confirmed ok (eventually)
