### ISSUE TITLE
Issue locally storing WALLET to USB drive - Ironkey

### ISSUE THREAD

**Issue by uhw4ke** [bitcoin-solutions/multibit-hd#614] opened 2015-06-18 07:15 UTC
Bug report
  Operating System: Windows 8.1
  MultiBit Version: MultiBit HD Release 0.1
  Steps to replicate the problem: Using USB drive anywhere but my PC

I'm having trouble storing my wallet on my secure Ironkey USB drive on windows.
I'm currently Running Multibit HD Latest version as of now, installed my Ironkey flash drive.

I created a 'multibit.properties' file and deleted the file extension .txt so it would store the wallet file locally to the usb...
I'm not sure if this method applies to the HD version of Multibit but cannot find information pertaining to how to store a wallet locally on the usb with Multibit HD. I don't see a .wallet file on my flash drive.

I know this text is redundant. Trying to be as descriptive as possible. Forgive me.

I first realized the file wasn't stored locally when I plugged my drive in on another computer and it initialized an install as opposed to having my wallet pop up with password requirements. How do I store my wallet locally to my USB flash drive? This is very crucial to me! :)

![nowallet](https://cloud.githubusercontent.com/assets/12948038/8226210/791c7afc-1551-11e5-8a50-e6487ea1d445.jpg)

**Comment by jim618** [comment] 2015-06-18 08:49
Hi uhw4ke,

Compared to MultiBit Classic, MultiBit HD has no configuration as to where the wallets are stored.

This is by design. We found that the seemingly straightforward option of letting users choose where to put theie wallet, including on removable media, created a whole host of problems (see below). For this reason there is no configuration as to where to store the MultiBit HD wallets and storing on removable media is not supported. Sorry.

There various problems created by more hetergeneous wallet locations were:
+ People would lose their wallets and raise a support issue. We would have no idea where they stored their wallets and they would get very frustrated.
+ People get confused by hidden directories and panic when they cannot find their wallets on disk
+ The failure rate for USB drives is _much_ higher than fixed disks when you take into account losses and breakages etc.
+ For removable drives the protocol handlers for 'bitcoin:' and 'payment request:' URIs don't get registered so users cannot click on links in browsers reliably etc. This gives a poor user experience.
+ Writing to removable drives can be problematic as people just yank them out and you get wallet write failures.

For MultiBit HD removable drives also introduce a single point of failure that invalidates a lot of the work we have done on automatic backups. The rolling backups and local zip backups are colocated with the wallet, so if you lose your USB drive you've also lost them. Also the cloud backup directory you have is very likely either to not to set or has been set to a directory on one computer that does not exist on another. You are thus more likely to lose 3 of the 4 possible recovery mechanisms (wallet words being the only remaining one, which won't recover all your metadata)

Overall the failure rate for storing wallets on removable media is too high for the intended user of MultiBit HD so we've chosen not to support it.

Regards,

Jim

**Comment by uhw4ke** [comment] 2015-06-18 12:12
This is unfortunate. I feel it is more secure. I don't see why you cannot add the functionality of storing a wallet on a removable flash drive at the end users expense and to cover your own trail by just making it known that such problems arise. At the same time a cloud recovery and wallet words can still be used to provide a strong level of recovery and security. I can see why this has been a problem with Multibit Classic... As such recovery options have not been provided to the extent of Multibit HD but for the sake of complete control over what someone does with THEIR WALLET I highly encourage the functionality of this feature. As it is not hard to create multiple backups of a wallet if you include this function.

Please reintroduce this function. As of now I will be using classic and/or armory until this feature is added back into Multibit HD.

Thank you for your prompt response.

**Comment by jim618** [comment] 2015-06-18 12:52
Thanks for your response uhw4ke.

I am 100% sure _you_ would make the appropriate backups (you've bought an IronKey after all !) but it is surprising how many people when we ask "Do you have a backup ?' in support calls there is an ominous silence.

As we want MultiBit HD to be used by non-techy people even a small error rate (say 1 in 10,000) will result in people losing their bitcoins. That's what we are trying to avoid.

**Comment by jim618** [comment] 2015-06-18 15:47
Closing as not implemented by design

**Closed by jim618** 2015-06-18 15:47 UTC
Labels: support
