### ISSUE TITLE
List of buttons not working in the UI

### ISSUE THREAD

**Issue by hughht5** [bitcoin-solutions/multibit-hd#461] opened 2015-03-12 11:38 UTC
Just as a background: I'm using OSX Yosemite on a mac pro retina. Below is a list of buttons that don't work in the UI

-----

In the request payment dialog if I click finish it doesn't close the window.

I have to quit and reopen the program to close the window.

----
Contacts tab doesnt open at all

**Comment by hughht5** [comment] 2015-03-12 11:40
The 'Send' button also doesn't do anything.

**Comment by hughht5** [comment] 2015-03-12 11:41
on the payments page - 'delete request' doesnt work (yes - after selecting a request to delete)

**Comment by hughht5** [comment] 2015-03-12 11:44
In 'manage wallet' - wallet dashboard and empty wallet both do nothing

**Comment by gary-rowe** [comment] 2015-03-12 11:54
That's some list! Thanks for the feedback (and keep 'em coming). Might be time for another log upload. 

I suspect this is all stemming from a single root cause.

**Comment by jim618** [comment] 2015-03-12 12:18
I suspect his payment db is not kosher and it's creating knock on problems (e.g. the change password)

**Comment by hughht5** [comment] 2015-03-12 12:22
Log files:
http://filebin.ca/1uZAauKI2vyZ

**Comment by jim618** [comment] 2015-03-17 13:10
Looking through the logs it appears that:
+ the wallet and history db loaded ok
+ the payments and contacts db failed to load as the AES decryption did not work.

The latter could fail if:
+ the password decrypting the db is not the one that encrypted it
or
+ the file has not written completely.

There are also some PKIX errors in the log which will be caused by SSL cert incompatibility but wouldn't cause the problems you are seeing.

I think more checking is required to validate the write of all of the encrypted dbs.

**Comment by hughht5** [comment] 2015-03-17 13:15
I did change the password once and it refuses the new one but accepts the
old one still.

Hugh

**Comment by jim618** [comment] 2015-03-17 13:15
This is related to #224, #225 and #407

**Comment by jim618** [comment] 2015-03-17 13:17
Hmm, it could be that the wallet password was changed but not the contacts/ payments.
I'll go back in the log history a bit more

**Comment by jim618** [comment] 2015-03-18 14:04
Proposed fix in #470 so marking as awaiting issue

**Comment by gary-rowe** [comment] 2015-04-01 20:30
This will require @hughht5 to verify on his machine using a 0.0.0 installer. Marking as "installer" pending close.

**Comment by jim618** [comment] 2015-04-02 11:00
I have uploaded a test installer for @hughht5 to test here:
https://beta.multibit.org/releases/multibit-hd/multibit-hd-0.0.0/

Awaiting review and closing

**Comment by jim618** [comment] 2015-04-08 10:12
I've closed this as neither @gary-rowe or I are seeing this problem.
@hughht5 if when you retest it it's still a problem open it again.

**Closed by jim618** 2015-04-08 10:12 UTC
Labels: awaiting review
