### ISSUE TITLE
Hook up Exit as default button in Exit/Switch panel

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#299] opened 2014-12-20 10:29 UTC
We don't have a default button set in the Exit/Switch panel which forces the user to use a mouse.

Suggest we hook up the Exit (or Switch, according to context) as the default button.

**Comment by jim618** [comment] 2015-03-03 11:03
Hooked up Exit/Switch to ENTER button on Exit confirm panel.

Ready for review and closing

**Comment by jim618** [comment] 2015-03-03 13:56
Well I have just spent an hour trying to get the Exit button to have a red background.
The moment it is set as the default button the background turns blue and that's that.
It's impossible to see in the wizard code where this painting is actually being done so I'm leaving it to @gary-rowe

**Comment by gary-rowe** [comment] 2015-03-03 14:09
You can see why I didn't pick this up earlier :-) 

No worries - it's a Swing thing. I'll sort it out.

**Comment by jim618** [comment] 2015-03-03 14:57
Yeah - like one of those maze adventure games . . . 
You are in a twisty corridor

**Comment by gary-rowe** [comment] 2015-03-03 16:42
Just a link to remind me: http://stackoverflow.com/a/12586568/396747

**Comment by gary-rowe** [comment] 2015-03-05 21:19
This is a lot more complex than it first appears. The problem is in selecting the correct color values from `NamedButtonRegionPainter` so that default appears correctly. It's a long, fiddly job to get right and can be put off until later.

**Comment by jim618** [comment] 2015-03-06 10:32
Not worth the effort.
Closing

**Closed by jim618** 2015-03-06 10:32 UTC
