### ISSUE TITLE
Users can produce more receiving addresses than gap limit

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#553] opened 2015-05-13 10:48 UTC
The gap limit for BIP32/44 wallets is 20 but we don't enforce this on the 'Request' button.
The user can generate as many payment requests as they like and if the first 20 are never paid there's a gap.

This won't affect MBHD but other wallets might have problems syncing from the same seed/ pub key.
This was raised here by reddit user kinoshitajona:
http://www.reddit.com/r/Bitcoin/comments/35puyz/synchronize_bip32_hd_wallet_between_phone_and/

Suggest enforce gap limit on display of request screen if there are 20 unpaid requests.

Gap limit is a bit nerdy to explain but most users won't encounter this message in normal use.

**Comment by gary-rowe** [comment] 2015-05-13 11:10
What if the user abandons those earlier requests (i.e. they are never going to get paid) and deletes them from Payments? I'm assuming that so long at least one of those addresses receives funds then the gap limit is reset to the most recent funded address. This means that we need to keep at least one open/available to ensure the user can recover from locking themselves out.

In terms of the UI, we will want a combination of:

* enable/disable the Request button depending on gap status
* ongoing note below the Request button to indicate that it is disabled: "Gap limit exceeded. See Help for details." 
* (we could extend this message area to also include a note about being disabled due to synchronization but that might just be obvious)
* warning alert each time they trigger the gap limit so they know this behaviour is generally wrong and they may need to spend their way out of it

The relevant section in BIP 44 is here: https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#Address_gap_limit

**Comment by jim618** [comment] 2015-05-13 11:18
Oh yeah it'll be a bit clumsy as it _seems_ like an unnecessary restriction but it's likely people will share seeds/ pubkeys between wallets.

Note that the spec states that it users should be _warned_ but we should probably make it not possible to make a gap (people ignore warnings, especially obtuse ones)

**Comment by wodry** [comment] 2015-05-17 21:09
I would suggest that there should be an extra confirmation question after clicking on "Delete request":
"Do You really want to delete this receiving address? You should not delete more than 20 unused receiving addresses, because that could lead to compatibility problems with other wallet software. You have already deleted x receiving addresses. Please check, that You really don't want to use this receiving address anymore."

**Comment by jim618** [comment] 2015-05-18 11:18
In economics there is a famous essay about a Broken Windown, written in 1850 by Frederic Bastiat:
http://www.econlib.org/library/Bastiat/basEss1.html

He introduces the principle of 'that which is seen and unseen'.

@wodry's last comment is similar: as we are in a thread about gap limits such a confirmation question makes sense. This is what is seen. However, what is NOT seen is that almost always someone deleting a payment request does not have to concern themselves with gap limits. It is a nerdy technical thing that 99% + users will never have to know about. Let's not bother them with this geeky stuff.

Thus it makes more sense only to inform users about gap limits when they actually hit it, which is on the click on the 'Request' button when a new address would create a BIP44 breaking gap.

**Comment by jim618** [comment] 2015-05-18 13:18
Note that the BIP32 spec does not mention gap limits:
https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

I propose we use the BIP44 gap limit of 20 for all the MBHD wallets on KISS grounds.

**Comment by jim618** [comment] 2015-05-19 15:30
Added in a check when Payment Request is opened. If the user is at the gap limit of 20 unpaid requests (since the last paid one) then the same receiving address is used.

The user gets a note to read the 'Gap limit' help article which I will write next.

Awaiting review and closing.

**Comment by gary-rowe** [comment] 2015-05-28 22:17
Just been checking this and I'm seeing a gap limit of less than 20 being enforced. My process was as follows:

1. Start with wallet containing a few old and deleted payment requests and some unconfirmed transactions (a bit messy)
1. Click Request until message appears. 9 items in list.
1. Send a payment to most recently generated address (shows up unconfirmed)
1. Start hammering the Request button. Additional 9 items in list before message.

![screen shot 2015-05-28 at 21 59 44](https://cloud.githubusercontent.com/assets/342133/7872313/f3a718b8-058e-11e5-8536-5d742f269a8e.png)

Since this could have been induced by a messy wallet, I continued as follows:

1. Perform a Repair Wallet - all transactions confirm (residue of the mempool issue?)
1. Send a payment to most recently generated address (shows up unconfirmed)
1. Once again hammer the Request button. Additional 8 items in list before message appears.

It may be that under the covers the gap limit is being handled correctly, but the UI is lacking sufficient feedback (e.g. deleted payment requests). There are a couple of ways to help the user (show paths/unused addresses etc) but since it is a corner case for the average mainstream user a bit of education about paying into the most recently generated address would probably be sufficient.

I'll bounce this back as I'm concerned that paying into a recent address didn't reset the gap to 20.

**Comment by jim618** [comment] 2015-05-29 14:10
I have pushed code that improves the gap calculation.

It checks more carefully the key usage and will now either return the gap or an Optional.absent() if the current algorithm cannot figure it out.

I have a wallet where the number of change addresses issues is 300, but the number of receive addresses is 90 or so. The algorithm doesn't work the gap out in this case but everywhere else it can work it out.

Given that this is 'an edge case of a wallet that probably would not be seen in production' I think this is ok for now.

We can always refine the gap algorithm in the future if we need to and the UI will respond appropriately.

Awaiting review (WalletService#gap is the method) and closing.

**Comment by jim618** [comment] 2015-05-29 15:06
I just did a seed restore of one of the wallets where the change addresses got ahead of the external addresses (for whatever reason - IDK) and the restore went fine and it is now correctly working out the gap.

**Comment by jim618** [comment] 2015-05-29 15:24
Looking at this a bit more:
+ the index for the EXTERNAL (receive) addresses get incremented every time the user presses the request button
+ the index for the INTERNAL (change) addresses gets incremented every time the user does a send

**Comment by gary-rowe** [comment] 2015-05-29 20:17
Verified working. The gap limit was around 11 in a messy wallet, but for a clean wallet is was 20 then after an unconfirmed spend to the most recent address permitted a further 20 to be generated. Thus we can safely say we adhere to BIP44.

Closing.

**Closed by gary-rowe** 2015-05-29 20:17 UTC
Labels: awaiting review
