### ISSUE TITLE
Export contact data as well as transactions

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#692] opened 2015-07-31 10:31 UTC
Currently contact information is a bit of an 'information silo' as a user cannot easily get it out of MBHD.

Suggest adding the ability for the user to export the data to CSV, in a similar way to the Transaction data.

It would also be possible to add import in a similar fashion but I suggest we stick with export only for now.

**Comment by gary-rowe** [comment] 2015-07-31 13:08
Duplicate of #112. Want to do some necromancy?

**Closed by gary-rowe** 2015-07-31 13:08 UTC
