### ISSUE TITLE
"Error reporting" window misses an "OK" button on reporting success

### ISSUE THREAD

**Issue by wodry** [bitcoin-solutions/multibit-hd#843] opened 2016-01-23 20:52 UTC
In the error reporting window, after clicking "send report" and report succeeded, the "send report" button is grey (deactivated) and there is only the "cancel" button left. Above the cancel button is the success message "Sending completed".

The user would have a better feeling if he could click "OK" after sending success. The cancel button should instead be activated after reporting success, because it has no use anymore.
I would like it, if the "send report" would change it's label to "OK" after sending success.

See screenshot.

![multibithd](https://cloud.githubusercontent.com/assets/8447873/12532741/99b0099c-c21b-11e5-9f0e-f3cf0bb1c25b.png)

**Comment by gary-rowe** [comment] 2016-01-23 21:34
Thanks for the feedback. This is a duplicate of #571 so closing here.

**Closed by gary-rowe** 2016-01-23 21:34 UTC
