### ISSUE TITLE
My password did not unlock wallet - password verified

### ISSUE THREAD

**Issue by kpitti** [bitcoin-solutions/multibit-hd#765] opened 2015-10-20 09:30 UTC
I can`t unlock and access my wallet. I try all options but I am getting this error:
![snimek obrazovky 2015-10-20 v 11 24 03](https://cloud.githubusercontent.com/assets/15210897/10603332/b9cb16a2-771d-11e5-9c47-7add7f1f6b89.jpg)

I check my password is correct using "wallet words".

**Comment by jim618** [comment] 2015-10-20 10:17
Try restoring one of your recent backups.
There is a how-to here:

https://multibit.org/en/help/hd0.1/restore-wallet.html

**Comment by kpitti** [comment] 2015-10-20 11:09
Thank you for hint. I try to restore recent backups, but it does not help. Then I went for older backup and now I can unlock with my password sucesfully.

**Comment by jim618** [comment] 2015-10-20 11:12
Ok great.
We think what the problem is that the wallet gets into an inconsistent state (most likely due to tx malleability but we haven't proven it yet). By restoring to an earlier backup the wallet can load and sync correctly.

I'll close this support query now (as we plan to look at the distral problem in the next release)

**Closed by jim618** 2015-10-20 11:12 UTC

**Comment by kpitti** [comment] 2015-10-20 11:15
OK, I agree. Thank you

**Comment by ooosername** [comment] 2016-05-29 15:39
I have this same problem.  Tried restoring all the backups shown and none work.  Completely stuck... Heeellllp!

**Comment by jaabbco** [comment] 2017-03-30 21:21
The same problem here. My bitcoins are stuck. What's the matter. Previous backups did not solve the problem. After completing last transaction and reciving btc, there was no equivalent in $ on the right hand side, like it is in case of other transactions. Please help.

**Comment by oniscoid** [comment] 2017-04-30 04:57
The same problem here. (Also there are recent posts on other forums of people having the same problem with MultiBitHD.)

My solution was to download the previous version (0.4.1) from https://multibit.org/releases/multibit-hd/multibit-hd-0.4.1/ and install it into a different directory, start it up, input my old password, and wait 5 minutes for it to synchronise. (And move coins to an Electrum wallet.)
