### ISSUE TITLE
I'm getting this when sending bitcoins "low spendable balance detected. Some of your bitcoins are tied up with ongoing transactions multibit"

### ISSUE THREAD

**Issue by michaelwmcgivern** [bitcoin-solutions/multibit-hd#715] opened 2015-09-01 20:13 UTC
![error](https://cloud.githubusercontent.com/assets/14080734/9615156/496f86a6-50ab-11e5-9344-d62055dd482b.png)

**Comment by gary-rowe** [comment] 2015-09-02 07:16
This is normal behaviour due to the way Bitcoin works. After some blocks confirm the message will disappear, the "Unconfirmed" balance will shift across to the main balance and you'll be able to continue creating more transactions.

From a technical standpoint this occurs when you are attempting to spend using "change outputs" from a parent transaction that 1) came from an external wallet, 2) has not yet confirmed.

See issue #540 for a more detailed explanation this situation.

**Comment by jim618** [comment] 2015-09-14 15:28
Nothin gto do so closing.

**Closed by jim618** 2015-09-14 15:28 UTC
