### ISSUE TITLE
Startup of MBHD is a bit slow compared to MB Classic

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#395] opened 2015-02-05 15:45 UTC
The start up sequence for MBHD is slower than MB Classic. It should be comparable in speed as it is basically doing the same.

Areas to look at for improvements:
+ lazy loading stuff at startup.
+ connecting to Bitcoin network.
+ making some of the wizard transitions/ handovers snappier

**Comment by gary-rowe** [comment] 2015-02-05 16:01
This is a duplicate of #382 so closing.

**Closed by gary-rowe** 2015-02-05 16:01 UTC
