### ISSUE TITLE
UnsupportedOperationException in getPeers with Tor

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#669] opened 2015-07-19 10:42 UTC
"_source": {
"@timestamp": "2015-07-12T12:16:01.197+02:00",
"level": "ERROR",
"thread_name": "PeerGroup Thread",
"logger_name": "org.bitcoinj.core.PeerGroup",
"message": "Peer discovery failure",
"stack_trace": "org.bitcoinj.net.discovery.PeerDiscoveryException: java.lang.UnsupportedOperationException
 at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:93) ~[multibit-hd.jar:na]
 at org.bitcoinj.core.PeerGroup.discoverPeers(PeerGroup.java:769) ~[multibit-hd.jar:na]
 at org.bitcoinj.core.PeerGroup$5.go(PeerGroup.java:478) [multibit-hd.jar:na]
 at org.bitcoinj.core.PeerGroup$5.run(PeerGroup.java:449) [multibit-hd.jar:na]
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_80]
 at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:27) [multibit-hd.jar:na]
 at java.lang.Thread.run(Unknown Source) [na:1.7.0_80]
 Caused by: java.lang.UnsupportedOperationException: null
 at com.subgraph.orchid.sockets.OrchidSocketImpl.setOption(OrchidSocketImpl.java:28) ~[multibit-hd.jar:na]
 at java.net.Socket.setSoTimeout(Unknown Source) ~[na:1.7.0_80]
 at com.squareup.okhttp.Connection.connect(Connection.java:154) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Call.getResponse(Call.java:262) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Call.execute(Call.java:79) ~[multibit-hd.jar:na]
 at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:82) ~[multibit-hd.jar:na]
 ... 11 common frames omitted
 ",
"level_value": 40000,
"@version": 1
},

**Comment by gary-rowe** [comment] 2015-07-24 09:32
Duplicate of #651 and fix is in #652.

Closing.

**Closed by gary-rowe** 2015-07-24 09:32 UTC
Labels: upload
