### ISSUE TITLE
PaymentsScreenView fails after showing credentials

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#610] opened 2015-06-16 19:47 UTC
User feedback indicates the following exception shortly after "Showing exiting credentials wizard after handover"

```
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value at com.google.common.base.Absent.get(Absent.java:47) ~[multibit-hd.jar:na] 
at org.multibit.hd.ui.views.screens.payments.PaymentsScreenView.initialiseScreenViewPanel(PaymentsScreenView.java:112) ~[multibit-hd.jar:na] 
at org.multibit.hd.ui.views.screens.AbstractScreenView.getScreenViewPanel(AbstractScreenView.java:112) ~[multibit-hd.jar:na] 
at org.multibit.hd.ui.views.DetailView.onShowDetailScreen(DetailView.java:90) ~[multibit-hd.jar:na] 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_80] 
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_80] 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.7.0_80] 
at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.7.0_80] 
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[multibit-hd.jar:na] 
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[multibit-hd.jar:na] at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [multibit-hd.jar:na] 
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [multibit-hd.jar:na] at com.google.common.eventbus.EventBus.post(EventBus.java:275) [multibit-hd.jar:na] 
at org.multibit.hd.ui.events.view.ViewEvents.fireShowDetailScreenEvent(ViewEvents.java:462) [multibit-hd.jar:na] 
at org.multibit.hd.ui.views.SidebarView.handleTreeSelection(SidebarView.java:284) [multibit-hd.jar:na]
at org.multibit.hd.ui.views.SidebarView.access$300(SidebarView.java:41) [multibit-hd.jar:na] 
at org.multibit.hd.ui.views.SidebarView$2.mouseReleased(SidebarView.java:206) [multibit-hd.jar:na] 
...
```
This looks like the user didn't see the credentials light box or the sidebar was exposed somehow and received a click triggering the failure.

**Comment by jim618** [comment] 2015-07-06 14:51
Looks like a dupe / near dupe of #644 

Awaiting issue - propose close when #644 is closed.

**Comment by jim618** [comment] 2015-07-12 09:37
As #644 is closed I am closing this near dupe.

**Closed by jim618** 2015-07-12 09:37 UTC
Labels: awaiting issue, upload
