### ISSUE TITLE
Activating the wallet "Unlock" button when no wallet selected does not make sense

### ISSUE THREAD

**Issue by wodry** [bitcoin-solutions/multibit-hd#549] opened 2015-05-09 17:57 UTC
So I just build the current git code and started it.

Very nice Bitcoin splash image on startup!

Unfortunateley, my existing ~/.MultiBitHD wallet (if I remember correctly that should have been empty) created with older git code (at least with the 0.0.8beta I used that at last, IIRC) is not recognized. The "Switch your wallet by selecting from the list below" only shows two empty lines when clicking on the selection button (cannot make screenshot of that because of mouse click focus).
My user feedback:
I am unsure, if that's a display error, and there are really two wallets detected but with an invisible name.
If there is no wallet detected, the selection should be disabled to show that clear. Maybe, if no wallet detected, there should be only a screen stating "No wallets found. Select 'Restore' or 'Create' wallet" showing only that two buttons and nothing more.

So, now I thought hm, maybe just paste Your old wallet password and click "unlock".

So when pasting the wallet password, the "Unlock" button gets activated, see screenshot:
![multibithd](https://cloud.githubusercontent.com/assets/8447873/7551351/c1d900ac-f685-11e4-9a21-34114b5ddf27.jpg)

Does not really make sense in my eyes to unlock "nothing" ;)

So then comes the "Wallet startup" window, showing "Wallet loading ..." and nothing happens. The "Exit" and "Restore" buttons are available. Confusing. What now? Maybe restoring?

![multibithd](https://cloud.githubusercontent.com/assets/8447873/7551345/9f8824d8-f685-11e4-8125-f7ab08de0dfa.jpg)

Any chance to get my old wallet available again (but not via seed phrase retore. I have the password!) ? It's not really important since it should be empty, but I would like to keep it. Could You give a hint to what looking for in the debug log to see if something is detected but not shown because of older version or something?
The timestamps of the files in
/.MultiBitHD/mbhd-6b827e63-...
directory are from 2015-02-20 so at that time I used that wallet it seems.

**Comment by gary-rowe** [comment] 2015-05-09 18:19
Yep, that's a bug. The Unlock should not unlock unless there is a valid selection in the drop down. 

Also you should not see the Unlock screen if no wallets are present - it should prompt you during startup to create a soft wallet. It sounds like there are wallets present but they are being filtered for some reason but are accepted during startup. 

Can you verify that they are not present in the folder since it may be a strange [side-effect relating to Beta 7](https://beta.multibit.org/blog/2015/04/14/bip32-wallet-compatibility.html). The Beta 7 effect should not causing filtering of wallets, though so having some more data here would help.

**Comment by wodry** [comment] 2015-05-09 18:22
Could You please explain what do You mean with "verify that they are not present in the folder" ? I do not understand.

**Comment by wodry** [comment] 2015-05-09 18:54
So I can You give user feedback for this use case: If there are wallet directories for a Trezor wallet, there sould be a list of that wallets on MultiBit HD startup of available Trezor wallets that MultiBit HD knows because of earlier usage. Unfortunateley, the balance showed after unlocking the Trezor wallet, was not correct. It was was too low. So I exited MultiBit HD and checked the balance on mytrezor.com. There was the balance (of Account 1) ok.
So I tried three times again to unlock the Trezor in MultiBit HD again, but all the three times it got stucked after entering the pin, in state "Waking up" (on Trezor display). :(

**Comment by gary-rowe** [comment] 2015-05-09 19:05
OK, I think we're getting to the root of this. It appears that you have at least one Trezor ("hard") wallet but no "soft" wallets. During startup MBHD detected the hard wallets but didn't filter them appropriately for when the Trezor device wasn't attached. What should have happened is that a new "soft" wallet should have been created. 

Regarding the Restore button showing, I agree. It should be removed since the Previous button will allow the user to escape back to the unlock screen if the wallet load fails.

So we have three fixes stemming from this:

* fix the Unlock button responding to password entry 
* fix the wallet filtering during startup when only "hard" wallets are present
* remove the Restore button from the Wallet load screen

Thanks for the feedback!

**Comment by gary-rowe** [comment] 2015-05-09 19:07
Regarding the Trezor failing to unlock that's a separate issue. Would you mind raising a fresh one describing what you did to cause it to fail. If you could include firmware version as well that would help with debugging.

**Comment by gary-rowe** [comment] 2015-05-10 13:18
In the strange situation where the password screen shows without a wallet to select (startup logic later should prevent this) the Unlock button will no longer unlock. Code review is required to verify.

The Restore button is required for hard wallets to allow recovery from backups if the local wallet files could not be decrypted. In the case of soft wallets Restore is redundant since we can return to the password screen and use that one in the rare case of a failed load. Soft wallet startup will verify.

On startup the logic to determine if the welcome wizard should be shown is summarised as:

* Always prompt for a licence
* We have a wiped hardware wallet so need to initialise
* No soft wallets and no hardware wallet so need to create/restore one
* No wallets at all so need to create/restore one (either hard or soft)

Ready for review and close.

**Comment by jim618** [comment] 2015-05-10 13:47
Sorry Gary - you need to keep the restore button on the wallet load screen,

The "prev' button on the Wallet load report is ONLY enabled when the user enters an incorrect password.
This is to enable them to go back and reenter the password.
We DO NOT enable it normally as it is essential to always close down a wallet completely (as in a Switch) before opening another.
To not do so risks the bug we had before when one wallet writes with the password of another wallet that is just being entered. Also it complicates what happens when the user inserts a Trezor and we don't want to go there.
This is why we need a restore on the wallet load page and very limited previous.

**Comment by wodry** [comment] 2015-05-10 14:47
Looks great for my poor eyes

**Comment by gary-rowe** [comment] 2015-05-10 17:31
Good point. I've re-instated the Restore for soft wallets too.

Ready for review and close.

**Comment by jim618** [comment] 2015-05-11 10:41
Confirmed that unlock is not enabled when there are no soft wallets (only hard).
Confirmed Restore is on both password entry and wallet load report screens.
Note that the user was not taken directly to a create wallet screen with only a hard wallet present but the 'Create' button is right on the screen and they might want to just insert their Trezor so I think this is correct.

Closing.

**Closed by jim618** 2015-05-11 10:41 UTC
Labels: awaiting review
