### ISSUE TITLE
Could not create hardware wallet in "wipe trezor"

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#618] opened 2015-06-18 17:38 UTC
Crash on Wipe Trezor by the looks of it:
```
"_source": {
"@timestamp": "2015-06-10T14:00:31.390-06:00",
"level": "WARN",
"thread_name": "AWT-EventQueue-0",
"logger_name": "org.multibit.hd.core.services.CoreServices",
"message": "Could not create the hardware wallet.",
"stack_trace": "java.lang.NoClassDefFoundError: Could not initialize class org.hid4java.jna.HidApi 
at org.hid4java.HidDeviceManager.getAttachedHidDevices(HidDeviceManager.java:150) ~[multibit-hd.jar:na] at org.hid4java.HidDeviceManager.scan(HidDeviceManager.java:101) ~[multibit-hd.jar:na] 
at org.hid4java.HidDeviceManager.start(HidDeviceManager.java:58) ~[multibit-hd.jar:na] 
at org.hid4java.HidServices.<init>(HidServices.java:38) ~[multibit-hd.jar:na] 
at org.hid4java.HidManager.getHidServices(HidManager.java:25) ~[multibit-hd.jar:na] 
at org.multibit.hd.hardware.trezor.wallets.v1.TrezorV1HidHardwareWallet.<init>(TrezorV1HidHardwareWallet.java:90) ~[multibit-hd.jar:na] 
at org.multibit.hd.hardware.trezor.wallets.v1.TrezorV1HidHardwareWallet.<init>(TrezorV1HidHardwareWallet.java:68) ~[multibit-hd.jar:na] 
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_79] 
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_79] 
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_79] at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_79] at java.lang.Class.newInstance(Class.java:379) ~[na:1.7.0_79] at org.multibit.hd.hardware.core.wallets.HardwareWallets.newHardwareWallet(HardwareWallets.java:214) ~[multibit-hd.jar:na] at org.multibit.hd.hardware.core.wallets.HardwareWallets.newUsbInstance(HardwareWallets.java:105) ~[multibit-hd.jar:na] at org.multibit.hd.core.services.CoreServices.getOrCreateHardwareWalletService(CoreServices.java:352) ~[multibit-hd.jar:na] at org.multibit.hd.ui.views.wizards.use_trezor.UseTrezorRequestWipeDevicePanelView.afterShow(UseTrezorRequestWipeDevicePanelView.java:93) [multibit-hd.jar:na] at org.multibit.hd.ui.views.wizards.AbstractWizard$1.run(AbstractWizard.java:200) [multibit-hd.jar:na]
```

**Comment by gary-rowe** [comment] 2015-07-24 17:22
Bumped into 0.1.3

**Comment by gary-rowe** [comment] 2015-07-26 15:12
Duplicate of #673 which contains more detail. 

Closing.

**Closed by gary-rowe** 2015-07-26 15:12 UTC
Labels: trezor, upload
