### ISSUE TITLE
Remove Tor support

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#633] opened 2015-06-26 15:53 UTC
>"_index": "error-reports-0a716cd",
"_type": "log-entry",
"_id": "234",
"_score": null,
"_source": {
"@timestamp": "2015-06-25T18:28:00.070-04:00",
"level": "ERROR",
"thread_name": "PeerGroup Thread",
"logger_name": "org.bitcoinj.core.PeerGroup",
"message": "Peer discovery failure",
"stack_trace": "org.bitcoinj.net.discovery.PeerDiscoveryException: java.lang.UnsupportedOperationException
 at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:93) ~[multibit-hd.jar:na]
 at org.bitcoinj.core.PeerGroup.discoverPeers(PeerGroup.java:769) ~[multibit-hd.jar:na]
 at org.bitcoinj.core.PeerGroup$5.go(PeerGroup.java:478) [multibit-hd.jar:na]
 at org.bitcoinj.core.PeerGroup$5.run(PeerGroup.java:449) [multibit-hd.jar:na]
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.7.0_80]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.7.0_80]
 at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:27) [multibit-hd.jar:na]
 at java.lang.Thread.run(Unknown Source) [na:1.7.0_80]
 Caused by: java.lang.UnsupportedOperationException: null
 at com.subgraph.orchid.sockets.OrchidSocketImpl.setOption(OrchidSocketImpl.java:28) ~[multibit-hd.jar:na]
 at java.net.Socket.setSoTimeout(Unknown Source) ~[na:1.7.0_80]
 at com.squareup.okhttp.Connection.connect(Connection.java:154) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Call.getResponse(Call.java:262) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192) ~[multibit-hd.jar:na]
 at com.squareup.okhttp.Call.execute(Call.java:79) ~[multibit-hd.jar:na]
 at org.bitcoinj.net.discovery.HttpDiscovery.getPeers(HttpDiscovery.java:82) ~[multibit-hd.jar:na]
 ... 11 common frames omitted
 ",
"level_value": 40000,
"@version": 1

**Comment by gary-rowe** [comment] 2015-06-26 21:14
As noted in #634 we will need to give the user some feedback when a Tor failure is detected.

**Comment by gary-rowe** [comment] 2015-07-10 12:51
This is a duplicate of #651 and has the same solution which is covered in #652. I'll mark this as awaiting issue to ensure we don't forget to check this is fixed.

**Comment by jim618** [comment] 2015-07-31 10:44
I have (locally) updated to bitcoinj-0.13.1-alice-0.1.3 but am getting the following error when connecting via Tor:
```
3:56,227] DEBUG [safe-fixed-bitcoin-network-0] o.m.h.c.s.BitcoinNetworkService - Starting blockchain download . . . 
[2015-07-31 10:33:56,588] WARN  [Thread-6] c.s.o.d.DirectoryImpl - Certificate read for unknown directory authority with identity: 27b6b5996c426270a5c95488aa5bceb6bcc86956 
[2015-07-31 10:33:57,923] WARN  [Thread-6] c.s.o.d.c.ConsensusDocumentImpl - Consensus signed by unrecognized directory authority: 27b6b5996c426270a5c95488aa5bceb6bcc86956 
[2015-07-31 10:34:14,214] WARN  [DirectoryDownloadTask worker-0] c.s.o.d.d.DirectoryDownloadTask - Failed to download key certificates: Request /tor/keys/fp-sk/e8a9c45ede6d711294fadf8e7951f4de6ca56b58-86832be318b3775ac21b45d1896dcc92b27f3d8b+ed03bb616eb2f60bec80151114bb25cef515b226-cd7159a8de14bc6bdc7e5e1e51adc89e162fca08+585769c78764d58426b8b52b6651a5a71137189a-6b82b0ec44bd79cb0d1f1bb2a0c597e0fec71ae9+d586d18309ded4cd6d57c18fdb97efa96d330566-3a8218840c58f0f35b1eefaf3c39fe46fbac842b+80550987e1d626e3eba5e5e75a458de0626d088c-414e42cca5f51e7b0c020496ab0f4b7894fcd409+49015f787433103580e3b66a1707a00e60f2d15b-f98e385f2982778f50925f54f832e2fe744b5ed7+efcbe720ab3a82b99f9e953cd5bf50f7eefc7b97-193b238d2e74692fd16fd11404ac661399fc0a65+14c131dfc5c6f93646be72fa1401c02a8df2e8b4-34cabfa62e3f374d0d67f7bd3d104196baef18ba to directory (none) returned error code: 404 Not found 
[2015-07-31 10:34:26,420] WARN  [DirectoryDownloadTask worker-0] c.s.o.d.d.DirectoryDownloadTask - Failed to download key certificates: Request /tor/keys/fp-sk/e8a9c45ede6d711294fadf8e7951f4de6ca56b58-86832be318b3775ac21b45d1896dcc92b27f3d8b+ed03bb616eb2f60bec80151114bb25cef515b226-cd7159a8de14bc6bdc7e5e1e51adc89e162fca08+585769c78764d58426b8b52b6651a5a71137189a-6b82b0ec44bd79cb0d1f1bb2a0c597e0fec71ae9+d586d18309ded4cd6d57c18fdb97efa96d330566-3a8218840c58f0f35b1eefaf3c39fe46fbac842b+80550987e1d626e3eba5e5e75a458de0626d088c-414e42cca5f51e7b0c020496ab0f4b7894fcd409+49015f787433103580e3b66a1707a00e60f2d15b-f98e385f2982778f50925f54f832e2fe744b5ed7+efcbe720ab3a82b99f9e953cd5bf50f7eefc7b97-193b238d2e74692fd16fd11404ac661399fc0a65+14c131dfc5c6f93646be72fa1401c02a8df2e8b4-34cabfa62e3f374d0d67f7bd3d104196baef18ba to directory (none) returned error code: 404 Not found 
[2015-07-31 10:34:47,844] WARN  [DirectoryDownloadTask worker-0] c.s.o.d.d.DirectoryDownloadTask - Failed to download key certificates: Request /tor/keys/fp-sk/e8a9c45ede6d711294fadf8e7951f4de6ca56b58-86832be318b3775ac21b45d1896dcc92b27f3d8b+ed03bb616eb2f60bec80151114bb25cef515b226-cd7159a8de14bc6bdc7e5e1e51adc89e162fca08+585769c78764d58426b8b52b6651a5a71137189a-6b82b0ec44bd79cb0d1f1bb2a0c597e0fec71ae9+d586d18309ded4cd6d57c18fdb97efa96d330566-3a8218840c58f0f35b1eefaf3c39fe46fbac842b+80550987e1d626e3eba5e5e75a458de0626d088c-414e42cca5f51e7b0c020496ab0f4b7894fcd409+49015f787433103580e3b66a1707a00e60f2d15b-f98e385f2982778f50925f54f832e2fe744b5ed7+efcbe720ab3a82b99f9e953cd5bf50f7eefc7b97-193b238d2e74692fd16fd11404ac661399fc0a65+14c131dfc5c6f93646be72fa1401c02a8df2e8b4-34cabfa62e3f374d0d67f7bd3d104196baef18ba to directory (none) returned error code: 404 Not found 
[2015-07-31 10:34:56,358] ERROR [PeerGroup Thread] o.b.c.PeerGroup - Exception when starting up ! java.lang.RuntimeException: java.util.concurrent.TimeoutException
! at org.bitcoinj.core.PeerGroup$7.run(PeerGroup.java:881) ~[bitcoinj-core-0.13.1-alice-0.1.3.jar:na]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_40]
! at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_40]
! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_40]
! at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_40]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_40]
! at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292) [na:1.7.0_40]
! at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_40]
! at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_40]
! at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:35) [bitcoinj-core-0.13.1-alice-0.1.3.jar:na]
! at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
Caused by: ! java.util.concurrent.TimeoutException: null
! at com.subgraph.orchid.TorClient.waitUntilReady(TorClient.java:126) ~[orchid-1.1.1.jar:na]
! at org.bitcoinj.core.PeerGroup$7.run(PeerGroup.java:879) ~[bitcoinj-core-0.13.1-alice-0.1.3.jar:na]
!... 10 common frames omitted
```

**Comment by jim618** [comment] 2015-08-11 13:17
As the bump to bitcoinj 0.13.2 has not fixed this we've agreed to remove Tor support until it is fixed.

I have removed Tor support from:
+ BitcoinNetworkService
+ The FooterView
+ The Labs screen in Preferences.

It is stillin the localisation file and Configuration so that when we put it back we will still have any localisations and previous settings.

Awaiting review and closing.

**Comment by gary-rowe** [comment] 2015-08-12 21:12
Confirmed that I'm seeing the same Tor messages on several different networks. It's got to come out of Labs since it's not close to production quality at the moment. Still we have all the code so it can go back in once we're happy it's all working again.

Closing.

Link to website issue for reference (see [Website #248](https://github.com/bitcoin-solutions/multibit-website/issues/248))

**Closed by gary-rowe** 2015-08-12 21:12 UTC
Labels: awaiting review, upload
