### ISSUE TITLE
Create new (soft) wallet not invoked on (new MBHD install + Trezor hard wallet)

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#369] opened 2015-01-23 14:13 UTC
If you have a fresh install of MBHD and the first wallet you create is a Trezor hard wallet then you don't see the 'Create new wallet' wizard when you start it up again (with no Trezor plugged in).

you just get the password entry screen but with no wallets in the drop down box.
it's not a disaster but it would be nicer if the 'Create new (soft) wallet' was started automatically.

**Comment by gary-rowe** [comment] 2015-01-23 14:27
Yeah, this would need to be driven by wallet summary count rather than presence of YAML/licence acceptance.

**Comment by gary-rowe** [comment] 2015-06-15 11:07
This is essentially a duplicate of #549.

Closing.

**Closed by gary-rowe** 2015-06-15 11:07 UTC
