### ISSUE TITLE
Lighthouse: Would be nice if I could specify wallet word timestamps in non-MB format

### ISSUE THREAD

**Issue by mikehearn** [bitcoin-solutions/multibit-hd#390] opened 2015-02-04 18:09 UTC
To import a wallet from Lighthouse to Multibit HD isn't possible right now *just* because of the timestamp format in use. Ability to pick a date using a calendar widget or just typing it in would improve interop quite a bit.

**Comment by bitcoin-solutions** [comment] 2015-02-13 15:59
Hi Mike,
When the user 'really knows' the wallet creation date adding a timestamp wouldn't be a problem.
The problem is when the user is importing wallet words from 'somewhere else' and they guess.
"Oh it was about April last year'.
In that case the synced wallet will be inconsistent and broken.

If we only accept MBHD timestamps this lessens the chance of this happening.

I suggest we have it so that if there is no timestamp MBHD syncs from the earliest HD wallet date (which I think it does - will have to check). That will be a bit slower but safer.

This is similar to in MB Classic where we used to allow users to pick a date to replay their wallet from but it was eventually removed as being slightly too error prone.

**Comment by jim618** [comment] 2015-03-05 11:32
Brought forward to Beta 8 as we can use the Lighthouse wallet for BIP32 compatibility testing.
See : #445

**Comment by gary-rowe** [comment] 2015-03-05 11:35
Perhaps have the field be generous? If a MultiBit HD timestamp is detected then big tick, if an ISO8601 date is entered (2000-12-31) then a warning that this might not be 100% and user beware.

**Comment by jim618** [comment] 2015-03-05 11:38
What can they usefully do with that warning ? All they can reasonably do is carry on and if it's wrong they have the same broken wallet they would have without the warning.

Better I think that the sync takes a few minutes more and they _definitely_ have their tx and bitcoin to spend

**Comment by gary-rowe** [comment] 2015-03-05 12:01
Yeah. It's one of those situations that seems easy on the face of it only to turn into a nest of snakes when you dig into it. It simply has to be MultiBit HD timestamp or "beginning of time". It's the only way to be sure.

**Comment by mikehearn** [comment] 2015-03-05 19:34
I'm not sure I agree - the user is already writing down once piece of arbitrary numeric data (the words), the Lighthouse UI prompts them to write down the date too. I don't expect anyone to actually memorise the creation date. The only reason I'm not using the MBHD timestamp scheme is because I don't know what it actually is (is it documented anywhere?) and because being able to use a date picker control is convenient.

**Comment by gary-rowe** [comment] 2015-03-05 20:02
It's the number of days elapsed since Bitcoin genesis block with a modulo 97 checksum appended.

From [Dates.java](https://github.com/bitcoin-solutions/multibit-hd/blob/master/mbhd-core/src/main/java/org/multibit/hd/core/utils/Dates.java#L536):

```java
 /**
* <p>A seed timestamp is the number of days elapsed since Bitcoin genesis block with a modulo 97 checksum appended.
* This gives a short representation that avoids user error during input and works in all locales.</p>
*
* @return Create a new seed timestamp (e.g. "1850/07") in UTC
*/
public static String newSeedTimestamp() {
long genesisMidnight = bitcoinGenesis().toDateMidnight().toDateTime().getMillis();
long nowMidnight = Dates.midnightUtc().getMillis();
long days = (nowMidnight - genesisMidnight) / 86_400_000;
long modulo97 = days % 97;
return String.format("%d/%02d", days, modulo97);
}
```

**Comment by jim618** [comment] 2015-03-09 15:09
As part of the testing for #445 I have tested a Lighthouse wallet I have.
The test was to put some bitcoin on the wallet and then restore the wallet words using MBHD.
(I left the timestamp blank in MBHD).

After restore I correctly saw the transactions I put into the wallet, plus the previous transactions that I used to send some money a while ago to the Medic project.

This indicates that the restore in MBHD of BIP32 wallets is compatible with Lighthouse.

I have marked this as 'awaiting issue' (#445) as I haven't pushed the changes yet - still testing the wallet fix is ok.

**Comment by mikehearn** [comment] 2015-03-09 17:37
Cool, thanks. I didn't realise you could leave the timestamp field blank.

**Comment by gary-rowe** [comment] 2015-03-09 21:23
@mikehearn I've raised an issue to cover this. See #457.

**Comment by jim618** [comment] 2015-03-10 11:23
@gary-rowe As #445 is now awaiting review can you please try replicating the restore of a Lighthouse wallet from wallet words in MBHD. Just leave the timestamp blank.

**Comment by gary-rowe** [comment] 2015-03-10 20:31
Lighthouse wallet restored correctly.

Closing.

**Closed by gary-rowe** 2015-03-10 20:31 UTC
Labels: awaiting review
